/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeucombat;

/**
 *
 * @author licence
 */
public class CombatSolo extends javax.swing.JFrame {

    /**
     * Creates new form CombatSolo
     */
    private Joueur j1;
    private Joueur j2;
    private Menu m1;
    public int life;
    
    public CombatSolo() {
        initComponents();
        j1 = new Joueur();
        j2 = new Joueur();
        life = 20;
        j1.SetLife(life);
        j2.SetLife(life);
        System.out.println(life);
        Vie1.setText(String.valueOf(life));
        Vie2.setText(String.valueOf(life));
        m1 = new Menu();
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        ActionJ1 = new javax.swing.JButton();
        ActionJ2 = new javax.swing.JButton();
        LabelVie1 = new javax.swing.JLabel();
        Vie1 = new javax.swing.JLabel();
        LabelVie2 = new javax.swing.JLabel();
        Vie2 = new javax.swing.JLabel();
        Begin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ActionJ1.setText("Action");
        ActionJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionJ1ActionPerformed(evt);
            }
        });

        ActionJ2.setText("Action");
        ActionJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionJ2ActionPerformed(evt);
            }
        });

        LabelVie1.setText("Points de vie");

        Vie1.setText("jLabel2");

        LabelVie2.setText("Points de vie :");

        Vie2.setText("jLabel4");

        Begin.setText("Begin");
        Begin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ActionJ1)
                .addGap(199, 199, 199)
                .addComponent(Begin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(ActionJ2)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelVie1)
                .addGap(18, 18, 18)
                .addComponent(Vie1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelVie2)
                .addGap(36, 36, 36)
                .addComponent(Vie2)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelVie1)
                    .addComponent(Vie1)
                    .addComponent(LabelVie2)
                    .addComponent(Vie2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActionJ1)
                    .addComponent(ActionJ2)
                    .addComponent(Begin))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionJ1ActionPerformed
        // TODO add your handling code here:
        j1.setVisible(true);
    }//GEN-LAST:event_ActionJ1ActionPerformed

    private void ActionJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionJ2ActionPerformed
        // TODO add your handling code here:
        j2.setVisible(true);
    }//GEN-LAST:event_ActionJ2ActionPerformed

    private void BeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginActionPerformed
        if(j1.GetAction().equals("p"))
        {
            j1.Attack(j2);
        }
        if(j1.GetAction().equals("t"))
        {
            j1.Throw(j2);
        }
        if(j1.GetAction().equals("c"))
        {
            j1.Counter(j2);
        }
        
         if(j2.GetAction().equals("p"))
        {
            j2.Attack(j1);
        }
        if(j2.GetAction().equals("t"))
        {
            j2.Throw(j1);
        }
        if(j2.GetAction().equals("c"))
        {
            j2.Counter(j1);
        }
        
        if(j1.GetLife() <=0 || j2.GetLife() <= 0)
        {
            this.setVisible(false);
            m1.setVisible(true);
        }
        
        Vie1.setText(String.valueOf(j1.GetLife()));
        Vie2.setText(String.valueOf(j2.GetLife()));
    }//GEN-LAST:event_BeginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombatSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombatSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombatSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombatSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombatSolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionJ1;
    private javax.swing.JButton ActionJ2;
    private javax.swing.JButton Begin;
    private javax.swing.JLabel LabelVie1;
    private javax.swing.JLabel LabelVie2;
    private javax.swing.JLabel Vie1;
    private javax.swing.JLabel Vie2;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
