/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeucombat;

import static javafx.beans.binding.Bindings.or;

/**
 *
 * @author licence
 */
public class Joueur extends javax.swing.JFrame {

    /**
     * Creates new form Joueur
     */
    private int life;
    private String action;
    private String position = "haut";
    public Joueur() {
        initComponents();
    }

    public void SetLife(int life)
    {
        this.life = life;
    }
    
    public int GetLife()
    {
        return this.life;
    }
    
    public String GetAction()
    {
        return this.action;
    }
    
    public String GetPosition()
    {
        return this.position;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Haut = new javax.swing.JButton();
        Arriere = new javax.swing.JButton();
        Avant = new javax.swing.JButton();
        Bas = new javax.swing.JButton();
        Player = new javax.swing.JLabel();
        Punch = new javax.swing.JButton();
        Throw = new javax.swing.JButton();
        Hold = new javax.swing.JButton();
        Lancer = new javax.swing.JButton();
        Counter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Haut.setText("Haut");
        Haut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HautActionPerformed(evt);
            }
        });

        Arriere.setText("Arriere");
        Arriere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArriereActionPerformed(evt);
            }
        });

        Avant.setText("Avant");
        Avant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvantActionPerformed(evt);
            }
        });

        Bas.setText("Bas");
        Bas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasActionPerformed(evt);
            }
        });

        Player.setText("Joueur");

        Punch.setText("P");
        Punch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PunchActionPerformed(evt);
            }
        });

        Throw.setText("T");
        Throw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThrowActionPerformed(evt);
            }
        });

        Hold.setText("H");
        Hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoldActionPerformed(evt);
            }
        });

        Lancer.setText("Lancer");
        Lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancerActionPerformed(evt);
            }
        });

        Counter.setText("C");
        Counter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Haut)
                    .addComponent(Bas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Hold)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Counter)
                        .addGap(93, 93, 93))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Arriere)
                .addGap(157, 157, 157)
                .addComponent(Avant)
                .addGap(63, 63, 63)
                .addComponent(Punch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(Throw)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(Player))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(Lancer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Player)
                .addGap(48, 48, 48)
                .addComponent(Haut)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arriere)
                    .addComponent(Avant)
                    .addComponent(Punch)
                    .addComponent(Throw))
                .addGap(122, 230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Counter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Bas)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Hold)
                        .addGap(62, 62, 62)))
                .addComponent(Lancer)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunchActionPerformed
        action = "p";
    }//GEN-LAST:event_PunchActionPerformed

    private void HoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoldActionPerformed
        action = "h";
    }//GEN-LAST:event_HoldActionPerformed

    private void ThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThrowActionPerformed
        action = "t";
    }//GEN-LAST:event_ThrowActionPerformed

    private void LancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LancerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_LancerActionPerformed

    private void HautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HautActionPerformed
        position = "haut";
    }//GEN-LAST:event_HautActionPerformed

    private void AvantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvantActionPerformed
       position = "avant";
    }//GEN-LAST:event_AvantActionPerformed

    private void BasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasActionPerformed
        position = "bas";
    }//GEN-LAST:event_BasActionPerformed

    private void ArriereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArriereActionPerformed
        position = "arrière";
    }//GEN-LAST:event_ArriereActionPerformed

    private void CounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CounterActionPerformed
        action = "c";
    }//GEN-LAST:event_CounterActionPerformed

    public void Attack(Joueur j)
    {
        int damage = 1;
        if (j.GetAction().equals("h")  || (j.GetAction().equals("c") && j.GetPosition().equals(this.position)) )
        {
            damage = 0;
        }
        if (j.GetAction().equals("t"))
        {
            damage = 2;
        }
        
        j.life = j.life - damage;
    }
    
    public void Throw(Joueur j)
    {
        int damage = 1;
        if (j.GetAction().equals("p"))
        {
            damage = 0;
        }
        if (j.GetAction().equals("c"))
        {
            damage = 2;
        }
        
        j.life = j.life - damage;
    }
    
    public void Counter(Joueur j)
    {
        int damage = 1;
        if(!j.GetAction().equals("p") && !j.GetPosition().equals(j.GetPosition()))
        {
            damage = 0;
        }
        else
        {
            damage = 2;
        }
        
        j.life = j.life - damage;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Joueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Joueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Joueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Joueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Joueur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arriere;
    private javax.swing.JButton Avant;
    private javax.swing.JButton Bas;
    private javax.swing.JButton Counter;
    private javax.swing.JButton Haut;
    private javax.swing.JButton Hold;
    private javax.swing.JButton Lancer;
    private javax.swing.JLabel Player;
    private javax.swing.JButton Punch;
    private javax.swing.JButton Throw;
    // End of variables declaration//GEN-END:variables
}
